server:
  port: 8080

project:
  name: 'mobile-back-end'
  version: '0.0.1-SNAPSHOT'
  description: '@project.description@'
info:
  build:
    artifact: "mobile-back-end"
    name: "@project.name@"
    description: '@project.description@'
    version: '0.0.1-SNAPSHOT'

application:
  title: ${project.name}
  version: ${project.version}

spring:
  output:
    ansi:
      enabled:  ${SPRING_OUTPUT_ANSI_ENABLE:ALWAYS} #always

  banner:
    charset: ${SPRING_BANNER_CHARSET:UTF-8} #UTF-8;
    location: ${SPRING_BANNER_LOCATION:CLASSPATH:/BANNER.TXT} #classpath:/banner.txt;


  #Configuração do JPA para uso do Hibernate
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    show-sql: true



  #Configuração da origem do banco de dados
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/bellavisage2
    username: root
    password: aluno

